global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
